### ISSUE TITLE
ssl error

### ISSUE THREAD

**Issue by sarvagna** [hrbrmstr/Rforecastio#7]
Repeatedly getting Error in function (type, msg, asError = TRUE)  : 
  SSL certificate problem: unable to get local issuer certificate
Can you please add proxy and ssl.verifypeer parameters?

**Comment by hrbrmstr** [comment]
Give the push (just now) a try. I added a `...` parameter to both functions to you can pass anything to the `GET` config now

**Comment by sarvagna** [comment]
Works perfect! thanks
