### ISSUE TITLE
'units' argument not working

### ISSUE THREAD

**Issue by hzambran** [hrbrmstr/Rforecastio#8]
`now.us <- get_current_forecast(-38.5, -72.5, units="us")`
`now.si <- get_current_forecast(-38.5, -72.5, units="si")`

`us <- now.us$hourly[, "precipIntensity"][[1]]`
`si  <- now.si$hourly[, "precipIntensity"][[1]]`

`us` and `si` should be different, but in the current version they are the same...

**Comment by hrbrmstr** [comment]
This is what I get when I run the _exact_ same code (about a minute ago):

    now.us <- get_current_forecast(-38.5, -72.5, units="us")
    now.si <- get_current_forecast(-38.5, -72.5, units="si")
    
    now.us$hourly[, "precipIntensity"][[1]]
    ##  [1] 0.0215 0.0151 0.0074 0.0018 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000
    ## [12] 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000
    ## [23] 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0018
    ## [34] 0.0025 0.0036 0.0048 0.0054 0.0049 0.0037 0.0030 0.0031 0.0036 0.0041 0.0044
    ## [45] 0.0047 0.0050 0.0052 0.0053 0.0061
    
    now.si$hourly[, "precipIntensity"][[1]]
    ##  [1] 0.5461 0.3835 0.1880 0.0457 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000
    ## [12] 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000
    ## [23] 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0457
    ## [34] 0.0635 0.0914 0.1219 0.1372 0.1245 0.0940 0.0762 0.0787 0.0914 0.1041 0.1118
    ## [45] 0.1194 0.1270 0.1321 0.1346 0.1549

**Comment by hzambran** [comment]
Thank you very much for clarifying this. Now I also get different values. I think I might have used `units="uk"` instead of `units="us"`, and that is why I got the same values than for `units="si"` .

**Comment by hrbrmstr** [comment]
not a problem. rly glad it's working and that it's getting use!
